logging:
  level:
    com.example.geolocation: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

server:
  error:
    include-stacktrace: never
    include-message: never

jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
